language: java
sudo: required
install: true

addons:
  sonarqube:
    token:
      secure: "ZyEqmjgi84NpiCCyDaxVJhT6eS6Zrs/unbM5+Dn6tt0be9FL6hWytx/6/Cq1fHgRkM7FTPeLZDMpjJUXEf+KAlxUnRJxgXT/NluDIiaSrDU/r3WQCHZOJM1ZhODi98yi2/w6bnw07OF0pGzSk4ARB+V4sefn4zPRITfb9GPE6lakiKy00YIaAmj1bo95pnyLYEivT5ysiOCciHXDLXTu9GwC0CSM5j/z7uER7gRnmi9y2fU296zsHmg70PWE6yw6xWFo6RhxKBOgtruA/pjQEgOuN/sR/5YY+pherp+KxllLngwzOaLDA0XWeO3GKRy8Qlu0UBHf+pVOEj9ENbmL77e0ADRgyi/qngKBVNa3SvgBO0Wht4haUAE5gs7LGMdzb5xS0UgTrsJ6tocoj2DpdnDGzpkhTncTXDvCPGj4rQaydoIXZ3+CaUr7Gic5clOqscZlB4ZAyr5C5DlkAdC1lozNJgBJTDCWknkR8vYlkhfeRLDejdnGxOnuLBllkdt+toxZKyViMJ72uvSHf0B7CK8tPuRODp70noD2PmcomBtjELTXy8YUJ+y3SAPRtIYfoL5KuF4DDXcLdJFbZjjTR9zfukgKP5AOH+5ul7+HJ2RY6r43TDdkXhEzOmfAMLzuPnQzfFmdeExdqegbV/lpJEhfyPA35gT0yVVuL9mPPbY="
    github_token:
      secure: "QzBT9cfEqP7fRpQF/xMEvadHk4+B7+jhMX8csqXM9uWQuAHzFnMcKdrHiri4MIW1si5wKXIMTk2ccpD1YHpe1blHYFh+aC4VpTMrKoNwB4LgEXxTA2wwRCNwjyixZmNUNZSWjm84KhLM97rOON/JNZ8Im9259BzM1artpz/mPaa8BsxoT9k/1oD7M4Qd7vHb8u7FexVIoW9gUUZLQ90YUuWHSIbHqQFt4NzI2REDvWgQKJZG2UUFaSxyeZLQwQHWDFBghrWEosto1yVdhjimhA5Tuyl4Ee5XHCJRlqnVAWxPJvT7kWpxL0DracmGJ9A3erYKd7HFhddScgr3k8Dg96dMgln7/fb2GhGtbKejaMUGMok9/E2AOEYL0hAFdDLeeYoZu8PRJY9nVC5DbAwbk4Nvg6lADW6hYiGKVmUPtt7aJt/KrW5dgGm+OQTXBF9IQ7h/hT1gYk9Ui7ac4YE0BNtSjvtBH5RNQK8kBn61g5r1n0TOX7xJB/QD3MTVyyVNaVc34PxE19avOtZT3/6VvXQqGVpWjEae3cKMSspQRYrK5MueoGwHFuKVWUgeUGtmZ4hijBtZE1sAGmCkMU3iCohayiEsSuOH50nLGej6Txn01c066fIHVozIzJoQKTfMDjFeSHDv0B6jC8bNxkC6zIro5sbZ7T4ajOKZvIKtTXA="

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

jdk:
  - oraclejdk8

script:
  - ./gradlew build test jar sonarqube

after_success:
  - bash <(curl -s https://codecov.io/bash)
